"use client";
import {useEffect,useRef,useState,useCallback} from "react";
import {Music2,Plus,Search,Play,MapPin,ChevronRight,Layers3,Sparkles,Heart,Compass,Ticket,ArrowLeft,Bookmark,MessageCircle,Flag,Check,Clock,Camera,RefreshCw,Edit3,Headphones,Users} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Progress} from "@/components/ui/progress";
import {Checkbox} from "@/components/ui/checkbox";
import {Toaster} from "@/components/ui/sonner";
import {toast} from "sonner";
import {SESSIONS,VIEWS,viewLabel,sampleClips,coverage,switchTime,stamp,type Clip,type Interaction,type ConcertSession} from "@/lib/domain";
import {api,STATIC_SHOWCASE} from "@/lib/media";
import Discovery from "./discovery";
import CreateSession from "./create-session";
import SessionVideos from "./session-videos";
import {DEFAULT_FILTERS,DEFAULT_VIDEO_FILTERS,type DiscoveryFilters,type VideoFilters} from "@/lib/discovery";
import UploadDialog,{type UploadContext} from "./upload";
export default function Home(){
const[sessions,setSessions]=useState<ConcertSession[]>(SESSIONS);
const[creatingSession,setCreatingSession]=useState(false);
const[page,setPage]=useState("home");const[sessionId,setSessionId]=useState(sessions[0].id);const[song,setSong]=useState(sessions[0].songs[0]);const[tab,setTab]=useState("videos");const[filters,setFilters]=useState<DiscoveryFilters>(DEFAULT_FILTERS);const[videoFilters,setVideoFilters]=useState<VideoFilters>(DEFAULT_VIDEO_FILTERS);const[clips,setClips]=useState<Clip[]>(sampleClips());const[interactions,setInteractions]=useState<Interaction[]>([]);const[user,setUser]=useState("");const[aiEnabled,setAiEnabled]=useState(false);const[loadError,setLoadError]=useState("");const[loading,setLoading]=useState(true);
const[player,setPlayer]=useState<Clip|null>(null);const[time,setTime]=useState(0);const[videoError,setVideoError]=useState(false);const[upload,setUpload]=useState<UploadContext|null>(null);const[contribution,setContribution]=useState<Clip|null>(null);const[note,setNote]=useState("");const[noteMode,setNoteMode]=useState<"comment"|"marker"|"report">("comment");const[timed,setTimed]=useState(true);const[acting,setActing]=useState(false);const[info,setInfo]=useState(false);const[memoryTab,setMemoryTab]=useState("mine");
const video=useRef<HTMLVideoElement>(null);const nextSeek=useRef<number|null>(null);const resume=useRef(false);
const catalogRef=useRef(sessions);catalogRef.current=sessions;
const session=sessions.find(s=>s.id===sessionId)||sessions[0];
const homeScroll=useRef(0);const currentPage=useRef("home");const savedBeforeNavigation=useRef(false);
const cells=coverage(clips,sessionId,sessions);const filled=cells.filter(c=>c.clip).length;const sessionClips=clips.filter(c=>c.sessionId===sessionId);const mine=clips.filter(c=>c.owner===user);const saved=clips.filter(c=>interactions.some(a=>a.videoId===c.id&&a.userId===user&&a.kind==="save"));
const refresh=useCallback(async()=>{try{const data=await api("state");catalogRef.current=data.sessions||SESSIONS;setSessions(catalogRef.current);setClips(data.clips);setInteractions(data.interactions);setUser(data.user);setAiEnabled(data.aiEnabled);setLoadError("");}catch(e){setLoadError((e as Error).message);}finally{setLoading(false);}},[]);
useEffect(()=>{void refresh();},[refresh]);
useEffect(()=>{const navigate=()=>{const sessions=catalogRef.current;
 const[p,id]=location.hash.slice(1).split("/");
 if(p==="session"&&loading&&!sessions.some(s=>s.id===id))return;
 const next=p==="session"&&sessions.some(s=>s.id===id)?"session":p==="memory"?"memory":"home";
 if(currentPage.current==="home"&&next!=="home"&&!savedBeforeNavigation.current)homeScroll.current=window.scrollY; savedBeforeNavigation.current=false;
 currentPage.current=next;setPlayer(null);setPage(next);
 if(next==="session"){setSessionId(id);setSong(sessions.find(s=>s.id===id)!.songs[0]||"");setTab("videos");setVideoFilters(DEFAULT_VIDEO_FILTERS);}
 requestAnimationFrame(()=>requestAnimationFrame(()=>window.scrollTo({top:next==="home"?homeScroll.current:0,behavior:"instant"})));
 };navigate();window.addEventListener("hashchange",navigate);return()=>window.removeEventListener("hashchange",navigate);},[loading]);
function go(p:string,id?:string){if(currentPage.current==="home"&&p!=="home"){homeScroll.current=window.scrollY;savedBeforeNavigation.current=true;}setPlayer(null);location.hash=p+(id?"/"+id:"");}
useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(ctx.registerTool({name:"open_concert_session",description:"Navigate to one of the demo concert sessions. This does not upload or publish content.",inputSchema:{type:"object",properties:{sessionId:{type:"string",enum:sessions.map(s=>s.id)}},required:["sessionId"],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{const s=sessions.find(s=>s.id===input.sessionId);if(!s)throw new Error("Invalid session");go("session",s.id);await new Promise(r=>requestAnimationFrame(r));return {sessionId:s.id,date:s.date,songs:s.songs};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[sessions]);
function openClip(c:Clip,seek?:number){nextSeek.current=seek??c.fileStart;resume.current=false;setPlayer(c);setVideoError(false);setNote("");setNoteMode("comment");setTime(seek??c.fileStart);}
function startUpload(ctx:UploadContext={}){if(!user){toast.error("数据服务尚未就绪，请先重试连接");return;}setPlayer(null);setUpload(page==="session"&&!ctx.sessionId?{...ctx,sessionId}:ctx);}
async function publishDone(c:Clip){await refresh();go("session",c.sessionId);setVideoFilters(DEFAULT_VIDEO_FILTERS);setTab("videos");setContribution(c);}
async function action(kind:string){if(!player||!user)return;setActing(true);try{const active=interactions.some(a=>a.videoId===player.id&&a.userId===user&&a.kind===kind);await api("actions",{videoId:player.id,kind,active:!active});await refresh();}catch(e){toast.error((e as Error).message);}finally{setActing(false);}}
async function postNote(){if(!player||!note.trim())return;setActing(true);try{await api("actions",{videoId:player.id,kind:noteMode,text:note,at:noteMode==="report"||(!timed&&noteMode==="comment")?null:Math.floor(time)});setNote("");await refresh();toast.success(noteMode==="marker"&&player.owner!==user?"已提交，等待上传者确认":noteMode==="report"?"举报已记录":"已保存");}catch(e){toast.error((e as Error).message);}finally{setActing(false);}}
async function approve(id:string,approved:boolean){try{await api("approve",{id,approved});await refresh();toast.success(approved?"标记已公开":"建议已忽略");}catch(e){toast.error((e as Error).message);}}
function swap(target:Clip){if(!player)return;const t=switchTime(player,target,video.current?.currentTime||time,player.songs[0]);if(t===null){toast.info("这个位置暂时没有对应进度的片段");return;}nextSeek.current=t;resume.current=!!video.current&&!video.current.paused;setPlayer(target);setVideoError(false);setTime(t);toast.success("已到"+VIEWS.find(v=>v.id===target.view)?.name);}
function seek(t:number){if(video.current){video.current.currentTime=t;setTime(t);void video.current.play().catch(()=>{});}}
const Card=({clip:c}:{clip:Clip})=><button className="video-card" onClick={()=>openClip(c)}><div className={"thumbnail thumb-"+c.view}><img src={c.poster} alt="" loading="lazy"/><span className="view-label">{viewLabel(c.view)}</span><span className="card-play"><Play size={20} fill="currentColor"/></span><span className="duration">{stamp(c.duration)}</span></div><div className="card-copy"><strong>{c.description||"留住这一刻的现场"}</strong><p>{c.songs.join(" / ")||c.segment||"现场片段"} <span>· {c.author}</span></p><div className="mini-tags">{c.tags.slice(0,2).map(t=><span key={t}>#{t}</span>)}</div></div></button>;
return <div className="app-shell"><Toaster theme="light" position="top-center"/><header className="topbar"><a className="brand" href="#home" onClick={()=>go("home")}><span className="brand-icon"><Music2 size={22}/></span><strong>同一现场</strong><small>QQ 音乐 · 共创社区</small></a><nav><button className={page!=="memory"?"active":""} onClick={()=>go("home")}>现场广场</button><button className={page==="memory"?"active":""} onClick={()=>go("memory")}>我的记忆</button></nav></header><main>
{loadError&&<div className="service-error" role="alert"><span>{loadError} · 请重试以获取最新内容</span><button onClick={()=>void refresh()}><RefreshCw size={15}/>重试连接</button></div>}
{page==="home"&&<Discovery sessions={sessions} clips={clips} filters={filters} onFilters={setFilters} onOpen={id=>go("session",id)} onCreate={()=>setCreatingSession(true)}/>}
{page==="session"&&<><div className="breadcrumb"><button onClick={()=>go("home")}><ArrowLeft size={16}/>现场广场</button><span>/ {session.city}站 / {session.night}</span></div><section className={"session-summary tone-"+session.tone}><img src={session.cover} alt="现场氛围封面"/><div className="session-summary-copy">{!session.demo&&<span className="demo-tag">{session.kind==="unconfirmed"?"真实记录 · 归属待确认":"社区共建场次"}</span>}<h1>{session.artist} · {session.tour}</h1><p className="session-summary-date">{session.city} · {session.date||"日期待确认"} {session.time}</p><p>{session.venue} · {session.night}</p></div><button className="primary" onClick={()=>startUpload({sessionId})}><Plus size={17}/>上传本场视频</button></section>
{sessions.filter(s=>s.artist===session.artist&&s.city===session.city).length>1&&<div className="session-switch" aria-label="切换同城场次">{sessions.filter(s=>s.artist===session.artist&&s.city===session.city).map(s=><button key={s.id} className={s.id===sessionId?"selected":""} onClick={()=>go("session",s.id)}>{s.date} · {s.night}<small>{s.time}</small></button>)}</div>}
{tab==="tasks"&&cells.length>0&&<div className="progress-panel"><div><span className="eyebrow">OUR COLLECTIVE MEMORY</span><h3>{cells.length>0&&filled===cells.length?"这一晚，被我们一起点亮了":"还差 "+(cells.length-filled)+" 个视角，让这一晚更完整"}</h3><p>每一份记录，都让现场多一个入口。</p></div><div className="progress-value"><strong>{filled}<small> / {cells.length}</small></strong><Progress value={cells.length?filled/cells.length*100:0} aria-label="基础探索格补全进度"/><small>基础视角覆盖 · 重复上传不重复计数</small></div></div>}
<Tabs value={tab} onValueChange={setTab} className="concert-tabs"><TabsList variant="line" className="main-tabs"><TabsTrigger value="videos">现场视频</TabsTrigger><TabsTrigger value="songs">按歌曲探索</TabsTrigger><TabsTrigger value="moments">名场面</TabsTrigger><TabsTrigger value="tasks">补现场 <span className="count-badge">{cells.length-filled}</span></TabsTrigger></TabsList>
<TabsContent value="videos"><SessionVideos session={session} clips={clips} interactions={interactions} filters={videoFilters} onFilters={setVideoFilters} onPlay={openClip} onUpload={()=>startUpload({sessionId})}/></TabsContent>
<TabsContent value="songs"><div className="explore-layout"><aside className="setlist"><div className="setlist-heading"><Music2 size={18}/><strong>{session.demo?"歌曲目录":"这一晚的歌单"}</strong><span>{session.songs.length} 首</span></div>{[...session.songs,...new Set(sessionClips.flatMap(c=>c.songs).filter(s=>!session.songs.includes(s)))].map((s,i)=><button key={s} className={song===s?"selected":""} onClick={()=>setSong(s)}><span>{String(i+1).padStart(2,"0")}</span><strong>{s}</strong>{song===s?<div className="equalizer"><i/><i/><i/></div>:<small>{sessionClips.filter(c=>c.songs.includes(s)).length} 视角</small>}</button>)}<button className={song==="__other"?"selected":""} onClick={()=>setSong("__other")}><span>＋</span><strong>开场与其他环节</strong></button><p>{session.demo?"采用歌手真实作品，非本场实际曲序；自填曲目保留原标注。":"每晚歌单独立整理，待确认曲目由上传者补充。"}</p></aside><div className="song-content"><div className="section-title compact"><div><span className="eyebrow">{song==="__other"?"BEYOND THE SONG":"ONE SONG, MANY PERSPECTIVES"}</span><h2>{song==="__other"?"音乐之外的瞬间":song}</h2></div><button className="text-button" onClick={()=>startUpload({sessionId,song:song==="__other"?undefined:song})}><Plus size={15}/>补一个视角</button></div>{song!=="__other"&&<div className="perspective-map"><div className="stage-bar">STAGE · 舞台</div><div className="map-nodes">{VIEWS.map((v,i)=>{const c=sessionClips.find(c=>c.songs.includes(song)&&c.view===v.id);return <button key={v.id} className={c?"lit":""} onClick={()=>c?openClip(c):startUpload({sessionId,song,view:v.id})}><span className="node-icon">{c?<Camera size={20}/>:<Plus size={20}/>}</span><strong>{v.name}</strong><small>{c?c.author+" 已贡献":"等待你来补位"}</small></button>;})}</div><small className="map-caption">视角探索示意 · 点击换个位置</small></div>}<div className="video-grid">{sessionClips.filter(c=>song==="__other"?!!c.segment:c.songs.includes(song)).map(c=><Card key={c.id} clip={c}/>)}</div>{!sessionClips.some(c=>song==="__other"?!!c.segment:c.songs.includes(song))&&<div className="empty"><Camera/><h3>这个瞬间，等你来记录</h3><button className="primary" onClick={()=>startUpload({sessionId,song:song==="__other"?undefined:song})}>上传第一段现场</button></div>}</div></div></TabsContent>
<TabsContent value="moments"><div className="section-title"><h2>那些值得反复回看的瞬间</h2><span>点开视频，寻找时间轴上的彩蛋</span></div><div className="video-grid moments-grid">{sessionClips.filter(c=>c.tags.some(t=>["全场合唱","舞台特效","歌手互动","安可"].includes(t))||interactions.some(a=>a.videoId===c.id&&a.kind==="marker"&&a.status==="approved")).map(c=><Card key={c.id} clip={c}/>)}</div></TabsContent>
<TabsContent value="tasks"><div className="section-title"><h2>一起拼完这张现场记忆</h2><span>{session.date} · {session.night}</span></div>{!session.songs.length&&<div className="empty"><Music2/><h3>这场演出的歌单，等你来补上</h3><button className="primary" onClick={()=>startUpload({sessionId})}>上传歌曲片段</button></div>}<div className="task-matrix"><div className="matrix-head"><span>歌曲 / 视角</span>{VIEWS.map(v=><span key={v.id}>{v.name}</span>)}</div>{session.songs.map(s=><div className="matrix-row" key={s}><strong>{s}</strong>{VIEWS.map(v=>{const cell=cells.find(c=>c.song===s&&c.view===v.id)!;return <button className={cell.clip?"complete":"missing"} key={v.id} onClick={()=>cell.clip?openClip(cell.clip):startUpload({sessionId,song:s,view:v.id})}>{cell.clip?<Check size={20}/>:<Plus size={20}/>}<span>{cell.clip?"已点亮":"我来补位"}</span><small>{cell.clip?.author||"等待你的记录"}</small></button>;})}</div>)}</div>{cells.length>0&&filled===cells.length&&<div className="celebration"><Sparkles/><h3>共同现场已点亮！</h3><p>继续上传，为这一晚增加更多值得回味的视角。</p></div>}</TabsContent></Tabs></>}
{page==="memory"&&<><div className="section-heading"><div><span className="eyebrow">MY LIVE MEMORIES</span><h1>我在现场留下的光<span>。</span></h1><p>每一段记录，都是回到那一晚的门票。</p></div><button className="primary" onClick={()=>startUpload()}><Plus size={16}/>上传我的现场</button></div><div className="memory-stats"><div><strong>{mine.length}</strong><span>我的贡献</span></div><div><strong>{saved.length}</strong><span>珍藏片段</span></div><div><strong>{interactions.filter(a=>a.kind==="comment"&&mine.some(c=>c.id===a.videoId)).length}</strong><span>收到的评论</span></div></div><Tabs value={memoryTab} onValueChange={setMemoryTab}><TabsList variant="line" className="main-tabs"><TabsTrigger value="mine">我的贡献</TabsTrigger><TabsTrigger value="saved">我的收藏</TabsTrigger><TabsTrigger value="review">待确认彩蛋</TabsTrigger></TabsList><TabsContent value="mine">{mine.length?<div className="video-grid moments-grid">{mine.map(c=><div key={c.id}><Card clip={c}/><div className="own-actions"><span>{sessions.find(s=>s.id===c.sessionId)?.date}</span><button onClick={()=>setContribution(c)}><Ticket size={14}/>贡献卡</button><button onClick={()=>startUpload({sessionId:c.sessionId,edit:c})}><Edit3 size={14}/>纠正归属</button></div></div>)}</div>:<div className="empty"><Ticket size={34}/><h3>你的第一张现场贡献卡，等你点亮</h3><p>上传一段现场，补上属于你的那个视角。</p><button className="primary" onClick={()=>startUpload()}>上传我的第一段</button></div>}</TabsContent><TabsContent value="saved">{saved.length?<div className="video-grid moments-grid">{saved.map(c=><Card key={c.id} clip={c}/>)}</div>:<div className="empty"><Bookmark/><h3>还没有收藏的片段</h3><button className="secondary" onClick={()=>go("home")}>去现场发现</button></div>}</TabsContent><TabsContent value="review">{interactions.filter(a=>a.kind==="marker"&&a.status==="pending"&&mine.some(c=>c.id===a.videoId)).length?interactions.filter(a=>a.kind==="marker"&&a.status==="pending"&&mine.some(c=>c.id===a.videoId)).map(a=><div className="review-row" key={a.id}><p>{stamp(a.at||0)} · {a.text}</p><button className="secondary" onClick={()=>openClip(mine.find(c=>c.id===a.videoId)!,a.at||0)}>查看片段</button><button className="primary" onClick={()=>void approve(a.id,true)}>确认公开</button><button className="text-button" onClick={()=>void approve(a.id,false)}>忽略</button></div>):<div className="empty"><Check/><h3>暂时没有待确认的彩蛋</h3><p>其他人标记你的片段时，会在这里等你确认。</p></div>}</TabsContent></Tabs></>}
<footer><span>同一现场 · 让每一个视角留住现场</span><button onClick={()=>setInfo(true)}>关于同一现场</button></footer></main><div className="mobile-nav"><button className={page!=="memory"?"active":""} onClick={()=>go("home")}><Compass/>现场</button><button className={page==="memory"?"active":""} onClick={()=>go("memory")}><Ticket/>我的</button></div>
<Dialog open={!!player} onOpenChange={open=>{if(!open)setPlayer(null);}}><DialogContent className="player-dialog">{player&&<><DialogTitle>{player.songs.join(" / ")||player.segment||"现场片段"} <span className="player-title-tag">{viewLabel(player.view)}</span></DialogTitle><DialogDescription>{sessions.find(s=>s.id===player.sessionId)?.date||"日期待确认"} · {sessions.find(s=>s.id===player.sessionId)?.city} · {player.author}的视角</DialogDescription><div className={"video-stage view-"+player.view}><video ref={video} key={player.id} src={player.src} controls playsInline preload="metadata" poster={player.poster} onLoadedMetadata={()=>{if(video.current&&nextSeek.current!==null){video.current.currentTime=nextSeek.current;nextSeek.current=null;if(resume.current)void video.current.play().catch(()=>{});}}} onTimeUpdate={()=>{if(video.current){setTime(video.current.currentTime);if(video.current.currentTime>=player.fileStart+player.duration){video.current.pause();}}}} onError={()=>setVideoError(true)}/>{videoError&&<div className="video-failure"><p>视频暂时无法播放</p><button className="secondary" onClick={()=>{setVideoError(false);video.current?.load();}}>重新加载</button></div>}</div>
{player.sample&&<p className="sample-source">{player.sessionId==="joker-sample"?"来源：你提供的《薛之谦演唱会.mp4》。保留完整片段与原声；当前仅有一个拍摄视角。":"影像来源：Alien Ant Farm · 2025 NAS Sigonella · U.S. Navy / Eloise Johnson。"}</p>}
<div className="view-switch"><strong><Layers3 size={16}/>换个位置</strong><div>{VIEWS.map(v=>{const target=clips.find(c=>c.sessionId===player.sessionId&&c.view===v.id&&c.songs.length===1&&player.songs.length===1&&c.songs[0]===player.songs[0]&&switchTime(player,c,time,player.songs[0])!==null);return <button key={v.id} className={player.view===v.id?"selected":""} onClick={()=>{if(v.id===player.view)return;if(target)swap(target);else startUpload({sessionId:player.sessionId,song:player.songs[0],view:v.id});}}>{v.name}<small>{v.id===player.view?"当前视角":target?"保持演唱进度":"这段暂缺 · 去补位"}</small></button>;})}</div></div>
<div className="moment-strip"><Sparkles size={16}/><strong>现场彩蛋</strong>{player.sample&&<button onClick={()=>seek(player.sessionId==="joker-sample"?18:player.fileStart+8)}>{player.sessionId==="joker-sample"?"彩带与灯海 · 00:18":"精彩瞬间 · 00:08"}</button>}{interactions.filter(a=>a.videoId===player.id&&a.kind==="marker"&&a.status==="approved").map(a=><button key={a.id} onClick={()=>seek(a.at||0)}>{stamp(a.at||0)} · {a.text}</button>)}<button onClick={()=>{setNoteMode("marker");setNote("");}}>＋ 标记当前瞬间</button></div>
<div className="interaction-bar"><button disabled={acting||!user} className={interactions.some(a=>a.videoId===player.id&&a.userId===user&&a.kind==="like")?"selected":""} onClick={()=>void action("like")}><Heart size={18}/> {interactions.filter(a=>a.videoId===player.id&&a.kind==="like").length||"喜欢"}</button><button disabled={acting||!user} className={interactions.some(a=>a.videoId===player.id&&a.userId===user&&a.kind==="save")?"selected":""} onClick={()=>void action("save")}><Bookmark size={18}/>收藏</button><button onClick={()=>setNoteMode("comment")}><MessageCircle size={18}/>交流</button><button onClick={()=>{setNoteMode("report");setNote("");}}><Flag size={15}/>举报</button>{player.owner===user&&<button onClick={()=>startUpload({sessionId:player.sessionId,edit:player})}><Edit3 size={15}/>纠正</button>}</div>
<div className="comment-compose"><label>{noteMode==="marker"?"给 "+stamp(time)+" 的瞬间起个名字":noteMode==="report"?"描述需要处理的问题":"聊聊这一刻"}<textarea className="field" rows={2} maxLength={500} placeholder={noteMode==="report"?"例如：内容来源或侵权问题":noteMode==="marker"?"例如：这一秒，全场一起挥手":"那一句唱到心里了……"} value={note} onChange={e=>setNote(e.target.value)}/></label><div>{noteMode==="comment"&&<label className="time-check"><Checkbox checked={timed} onCheckedChange={v=>setTimed(!!v)}/>关联 {stamp(time)}</label>}<button className="primary" disabled={acting||!note.trim()||!user} onClick={()=>void postNote()}>{noteMode==="marker"?"提交彩蛋":noteMode==="report"?"提交举报":"发送评论"}</button></div></div>
<div className="comment-list">{interactions.filter(a=>a.videoId===player.id&&a.kind==="comment").map(a=><div key={a.id}><span className="avatar">{a.userId===user?"我":"友"}</span><div><strong>{a.userId===user?"我":"现场同好"}</strong><p>{a.at!==null&&<button onClick={()=>seek(a.at!)}>{stamp(a.at)}</button>}{a.text}</p></div></div>)}</div></>}</DialogContent></Dialog>
{creatingSession&&<CreateSession sessions={sessions} onClose={()=>setCreatingSession(false)} onCreated={async s=>{await refresh();setFilters({...DEFAULT_FILTERS,period:"all"});go("session",s.id);}}/>}
{upload&&<UploadDialog sessions={sessions} key={upload.edit?.id||"new"} context={upload} onClose={()=>setUpload(null)} onPublished={publishDone} aiEnabled={aiEnabled}/>}
<Dialog open={!!contribution} onOpenChange={open=>{if(!open)setContribution(null);}}><DialogContent className="contribution-dialog"><DialogTitle>你为这一晚，添了一束光</DialogTitle><DialogDescription>我的现场贡献卡</DialogDescription>{contribution&&<div className="contribution-ticket"><Ticket size={34}/><span className="eyebrow">I WAS PART OF THE MEMORY</span><h2>{contribution.songs.join(" / ")||contribution.segment||"现场片段"}</h2><p>{sessions.find(s=>s.id===contribution.sessionId)?.date||"日期待确认"} · {sessions.find(s=>s.id===contribution.sessionId)?.city}</p><strong>{viewLabel(contribution.view)} · 已贡献</strong><div className="ticket-line"/><p>{contribution.description||"谢谢你，让现场多一个入口。"}</p></div>}<button className="primary" onClick={()=>{if(contribution)go("session",contribution.sessionId);setContribution(null);}}>回到共同现场</button></DialogContent></Dialog>
<Dialog open={info} onOpenChange={setInfo}><DialogContent><DialogTitle>关于同一现场</DialogTitle><DialogDescription>同一晚的演出，不同位置的记忆。</DialogDescription><div className="info-copy"><p>找到你去过的演出，分享自己的现场记录。社区还没有收录的场次，可以在现场广场新增，再进入场次上传视频。</p><p>当前预置场次的日期与场馆尚未核实，歌曲目录收录歌手作品。预置影像来自 Alien Ant Farm 现场，具体来源见下方链接。</p><p>歌手头像来自 QQ 音乐歌手资料。封面摄影：<a href="https://unsplash.com/photos/group-of-people-attending-a-performance-8XLapfNMW04" target="_blank" rel="noreferrer">Yvette de Wit / Unsplash</a>。影像来源：<a href="https://commons.wikimedia.org/wiki/File:InFocus-_Alien_Ant_Farm_Concert_(968945).webm" target="_blank" rel="noreferrer">U.S. Navy / Eloise Johnson</a>。</p>{aiEnabled&&!STATIC_SHOWCASE&&<p>使用 AI 标签建议时，会将最多三张代表画面发送给 AI 服务。场次与歌曲始终以你的选择为准。</p>}<p>{STATIC_SHOWCASE?"视频和互动记录在当前页面内临时保留，刷新或关闭页面后清除。":"你的上传、收藏与贡献保存在当前访客身份下。请保留浏览器数据，以便再次找回自己的记录。"}</p>{STATIC_SHOWCASE&&<button className="text-button" onClick={async()=>{setPlayer(null);await api("demo/switch-user",{});await refresh();}}>当前访客：{user==="demo-2"?"晚风来信":"追光的人"} · 切换身份</button>}</div></DialogContent></Dialog>
</div>}


