"use client";
import {Camera,Heart,Play,Search} from "lucide-react";
import {SEGMENTS,VIEWS,stamp,type Clip,type ConcertSession,type Interaction} from "@/lib/domain";
import {DEFAULT_VIDEO_FILTERS,listSessionVideos,type VideoFilters} from "@/lib/discovery";

export default function SessionVideos({session,clips,interactions,filters,onFilters,onPlay,onUpload}:{session:ConcertSession;clips:Clip[];interactions:Interaction[];filters:VideoFilters;onFilters:(value:VideoFilters)=>void;onPlay:(clip:Clip)=>void;onUpload:()=>void}){
 const own=clips.filter(c=>c.sessionId===session.id);
 const songs=[...new Set([...session.songs,...own.flatMap(c=>c.songs)])];
 const videos=listSessionVideos(clips,interactions,session.id,filters);
 const change=(value:Partial<VideoFilters>)=>onFilters({...filters,...value});
 return <section className="session-videos"><div className="video-list-toolbar"><span className="video-list-count">{videos.length} 个现场视频</span><div className="video-filters"><select aria-label="筛选歌曲或环节" value={filters.content} onChange={e=>change({content:e.target.value})}><option value="">全部歌曲与环节</option><optgroup label="歌曲">{songs.map(s=><option key={s} value={`song:${s}`}>{s}</option>)}</optgroup><optgroup label="其他环节">{SEGMENTS.map(s=><option key={s} value={`segment:${s}`}>{s}</option>)}</optgroup></select><select aria-label="筛选视角" value={filters.view} onChange={e=>change({view:e.target.value})}><option value="">全部视角</option>{VIEWS.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><select aria-label="视频排序" value={filters.sort} onChange={e=>change({sort:e.target.value as VideoFilters["sort"]})}><option value="latest">最新发布</option><option value="likes">最多喜欢</option></select></div></div>
 <div className="video-list">{videos.map(c=><button className="video-list-row" key={c.id} onClick={()=>onPlay(c)}><span className="list-thumbnail"><img src={c.poster} alt="" loading="lazy"/><span className="list-play"><Play size={20} fill="currentColor"/></span><span className="duration">{stamp(c.duration)}</span></span><span className="video-row-copy"><strong>{c.description||"留住这一刻的现场"}</strong><span className="video-row-song">{c.songs.join(" / ")||c.segment}</span><span className="video-row-tags"><span>{VIEWS.find(v=>v.id===c.view)?.name}</span></span><span className="video-row-author">{c.author}<span> · {new Intl.DateTimeFormat("zh-CN",{timeZone:"Asia/Shanghai",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(c.createdAt))}</span></span></span><span className="video-row-likes"><Heart size={15}/>{new Set(interactions.filter(a=>a.kind==="like"&&a.videoId===c.id).map(a=>a.userId)).size}</span></button>)}</div>
 {!videos.length&&<div className="empty">{own.length?<Search/>:<Camera/>}<h3>{own.length?"没有符合条件的视频":"这晚的第一段记录，等你来分享"}</h3><p>{own.length?"试试其他歌曲或视角。":"上传你的现场，让同一晚的记忆在这里相遇。"}</p><button className="primary" onClick={own.length?()=>onFilters(DEFAULT_VIDEO_FILTERS):onUpload}>{own.length?"清除筛选":"上传本场视频"}</button></div>}
 </section>;
}
