"use client";
import {useEffect,useRef,useState} from "react";
import {UploadCloud,Sparkles,Check,Loader2,Video,Music2} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Checkbox} from "@/components/ui/checkbox";
import {VIEWS,TAGS,SEGMENTS,type Clip,type ConcertSession} from "@/lib/domain";
import {inspectVideo,api} from "@/lib/media";
import {toast} from "sonner";
import SessionChoice from "./session-choice";
import {EMPTY_SESSION,validateSession,findExistingSession,createCommunitySession,type SessionDraft} from "@/lib/sessions";
import SongSplitter from "./song-splitter";
import {type SongRange} from "@/lib/splitting";
import {type CutVideo} from "@/lib/video-split";
export type UploadContext={sessionId?:string;song?:string;view?:string;edit?:Clip};
export function Picker({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:{id:string;name:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="picker" aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i.id} value={i.id}>{i.name}</SelectItem>)}</SelectContent></Select>;}
export default function UploadDialog({sessions,context,onClose,onPublished,aiEnabled}:{sessions:ConcertSession[];context:UploadContext|null;onClose:()=>void;onPublished:(c:Clip)=>Promise<void>;aiEnabled:boolean}){
const[sessionMode,setSessionMode]=useState<"existing"|"new">("existing");const[draft,setDraft]=useState<SessionDraft>({...EMPTY_SESSION});
const[split,setSplit]=useState(false);const[ranges,setRanges]=useState<SongRange[]>([]);const[cuts,setCuts]=useState<CutVideo[]>([]);const[confirmed,setConfirmed]=useState(false);const[cutAssets,setCutAssets]=useState<string[]>([]);const batchId=useRef("");
const edit=context?.edit;const[sessionId,setSessionId]=useState(context?.sessionId||edit?.sessionId||"");const[songs,setSongs]=useState<string[]>(edit?.songs|| (context?.song?[context.song]:[]));const[segment,setSegment]=useState(edit?.segment||"");const[view,setView]=useState(edit?.view||context?.view||"front");const[tags,setTags]=useState<string[]>(edit?.tags||[]);const[description,setDescription]=useState(edit?.description||"");const[file,setFile]=useState<File|null>(null);const[media,setMedia]=useState<{duration:number;poster:string;frames:string[];src:string}|null>(null);const[busy,setBusy]=useState("");const[error,setError]=useState("");const[aiNote,setAiNote]=useState("");const[search,setSearch]=useState("");const[custom,setCustom]=useState("");const[artist,setArtist]=useState("");const[step,setStep]=useState(1);const[assetId,setAssetId]=useState("");const input=useRef<HTMLInputElement>(null);
useEffect(()=>()=>{if(media)URL.revokeObjectURL(media.src);},[media]);
useEffect(()=>()=>{cuts.forEach(c=>URL.revokeObjectURL(c.src));},[cuts]);
function replaceCuts(next:CutVideo[]){setCuts(next);setCutAssets([]);batchId.current=crypto.randomUUID();}
let validDraft:SessionDraft|undefined;let draftError="";if(sessionMode==="new"){try{validDraft=validateSession(draft);}catch(e){draftError=(e as Error).message;}}
const duplicate=validDraft?findExistingSession(validDraft,sessions):undefined;
const session=sessionMode==="new"?(duplicate||(validDraft?createCommunitySession(validDraft,"draft",""):undefined)):sessions.find(s=>s.id===sessionId);const toggle=(s:string)=>{setSegment("");setSongs(songs.includes(s)?songs.filter(x=>x!==s):[...songs,s]);};
async function choose(f:File){setBusy("读取视频");setError("");setFile(null);setMedia(null);setAssetId("");setRanges([]);replaceCuts([]);setConfirmed(false);try{const m=await inspectVideo(f);setMedia(m);setFile(f);setAiNote("");}catch(e){setError((e as Error).message);}finally{setBusy("");}}
async function analyze(){if(!media)return;setBusy("AI 正在查看代表画面");setError("");try{const{suggestion:s}=await api("analyze",{frames:media.frames,duration:media.duration});if(s.view!=="unknown")setView(s.view);setTags(s.tags);setDescription(s.description);setAiNote("AI 建议 · "+s.uncertainty+" 可修改后发布。");}catch(e){setError((e as Error).message);}finally{setBusy("");}}
async function publish(){setBusy("正在发布");setError("");try{if(!session)throw new Error("请选择已有场次或填写完整的新场次");const targetId=session.id;const newSession=sessionMode==="new"?validateSession(draft):undefined;if(split&&!edit){if(!cuts.length||cuts.length!==ranges.length||!confirmed)throw new Error("请先确认分段并生成单曲视频");const posters=await Promise.all(cuts.map(async c=>{const m=await inspectVideo(c.file);URL.revokeObjectURL(m.src);return m.poster;}));const keys=[...cutAssets];for(let i=0;i<cuts.length;i++){if(keys[i])continue;setBusy(`正在上传第 ${i+1}/${cuts.length} 首`);const r=await fetch("/api/upload",{method:"POST",headers:{"Content-Type":cuts[i].file.type},body:cuts[i].file});const result:any=await r.json();if(!r.ok)throw new Error(result.error);keys[i]=result.id;setCutAssets([...keys]);}setBusy("正在发布单曲片段");const result=await api("videos/batch",{requestId:batchId.current,newSession,clips:cuts.map((c,i)=>({sessionId:targetId,songs:[ranges[i].song],segment:"",view,tags,description,assetId:keys[i],duration:c.duration,poster:posters[i]}))});await onPublished(result.clips[0]);toast.success(`已发布 ${result.clips.length} 个单曲片段，每首歌独立归档`);onClose();return;}let key=assetId;if(!edit&&!key){if(!file||!media)throw new Error("请先选择可播放的视频");const r=await fetch("/api/upload",{method:"POST",headers:{"Content-Type":file.type},body:file});const result:any=await r.json();if(!r.ok)throw new Error(result.error);key=result.id;setAssetId(key);}const{clip}=await api("videos"+(edit?"/"+edit.id:""),{sessionId:targetId,newSession,songs,segment,view,tags,description,assetId:key,duration:media?.duration,poster:media?.poster});await onPublished(clip);toast.success(edit?"现场归属已更新":"你的视角已加入共同现场");onClose();}catch(e){setError((e as Error).message);}finally{setBusy("");}}
return <Dialog open={!!context} onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className="upload-dialog"><DialogTitle>{edit?"纠正我的现场记录":"把你的那一刻，放进来"}</DialogTitle><DialogDescription>{edit?"修改后，内容会移到正确的场次与歌曲。":"选择社区已有场次，或创建你第一位记录的演出。"}</DialogDescription><div className="steps"><span className={step===1?"active":""}>01 选择与归档</span><span className={step===2?"active":""}>02 标签与发布</span></div>
{step===1?<fieldset disabled={!!busy} className="form-stack upload-fields">{!edit&&<><input ref={input} type="file" accept="video/mp4,video/webm,video/quicktime" className="sr-only" aria-label="选择视频文件" onChange={e=>{const f=e.target.files?.[0];if(f)void choose(f);}}/><button className="upload-zone" onClick={()=>input.current?.click()} disabled={!!busy}>{media?<><Video/><strong>{file?.name}</strong><small>{Math.round(media.duration)} 秒 · 点击更换</small></>:<><UploadCloud size={30}/><strong>选择你的现场视频</strong><small>MP4 / WebM / MOV · 最大 25 MB</small></>}</button></>}
<SessionChoice sessions={sessions} mode={sessionMode} onMode={mode=>{setSessionMode(mode);setSongs([]);setSegment("");setError("");}} sessionId={sessionId} onChoose={id=>{setSessionId(id);setSongs([]);setSegment("");setError("");}} search={artist} onSearch={setArtist} draft={draft} onDraft={setDraft} duplicate={duplicate}/><p className="helper">{session?session.venue+(sessionMode==="new"&&!duplicate?" · 将与第一条视频一起创建。":" · 请核对日期，同城每晚独立归档。"):sessionMode==="new"?draftError:"请主动选择你拍摄的演出场次。"}</p>
<label>这段视频唱了什么？<input className="field" value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索本场曲目"/></label><div className="song-checks">{[...new Set([...(session?.songs||[]),...songs])].filter(s=>s.includes(search)).map(s=><label key={s}><Checkbox checked={songs.includes(s)} onCheckedChange={()=>toggle(s)}/>{s}{!session?.songs.includes(s)&&<small>待确认曲目</small>}</label>)}</div><div className="inline-form"><input className="field" placeholder="找不到？填写歌曲名" value={custom} maxLength={60} onChange={e=>setCustom(e.target.value)}/><button className="secondary" onClick={()=>{const s=custom.trim();if(s){setSegment("");setSongs([...new Set([...songs,s])]);setCustom("");setSearch("");}}}>添加</button></div><label>或选择其他环节<Picker label="其他环节" value={segment||"none"} onChange={v=>{setSegment(v==="none"?"":v);if(v!=="none")setSongs([]);}} items={[{id:"none",name:"歌曲演唱"},...SEGMENTS.map(s=>({id:s,name:s}))]}/></label>{!edit&&media&&file&&<><div className="upload-modes"><button className={!split?"selected":""} onClick={()=>setSplit(false)}>完整视频上传</button><button className={split?"selected":""} onClick={()=>{setSplit(true);setSegment("");}}>按单首歌曲拆分</button></div>{split&&<SongSplitter file={file} duration={media.duration} src={media.src} songs={[...new Set([...songs,...(session?.songs||[])])]} ranges={ranges} onRanges={setRanges} cuts={cuts} onCuts={replaceCuts} confirmed={confirmed} onConfirmed={setConfirmed} busy={busy} setBusy={setBusy} onError={setError}/>}</>}{songs.length>1&&!split&&<p className="helper">跨多首歌的整段视频会关联各首歌曲；选择「按单首歌曲拆分」，可生成独立视频。</p>}</fieldset>:<div className="form-stack">
{media&&<img className="frame-preview" src={media.frames[1]} alt="上传视频代表画面"/>}{aiEnabled&&<button className="ai-button" disabled={!!busy||!media} onClick={()=>void analyze()}><Sparkles size={17}/>AI 帮我整理片段</button>}{aiNote&&<p className="ai-note">{aiNote}</p>}<label>拍摄视角<Picker label="拍摄视角" value={view} onChange={setView} items={VIEWS.map(v=>({id:v.id,name:v.name}))}/></label><label>片段内容</label><div className="tag-options">{TAGS.map(t=><button className={tags.includes(t)?"selected":""} key={t} onClick={()=>setTags(tags.includes(t)?tags.filter(x=>x!==t):[...tags,t])}>{tags.includes(t)&&<Check size={13}/>} {t}</button>)}</div><label>写下这一刻<textarea className="field" rows={3} maxLength={500} value={description} onChange={e=>setDescription(e.target.value)} placeholder="灯亮起来的时候，我们一起唱了那一句……"/></label><div className="summary"><Music2 size={18}/><div><strong>{sessionMode==="new"&&!duplicate?"新建场次并发布首条记录":"发布到这里"}</strong><p>{session?.artist} · {session?.tour}</p><p>{session?.city} · {session?.date||"日期待确认"} {session?.time} · {session?.night}</p><p>{session?.venue}</p><p>{split?cuts.map((_,i)=>ranges[i].song).join(" / "):songs.join(" / ")||segment} · {VIEWS.find(v=>v.id===view)?.name}</p></div></div>{split&&<p className="ai-note">将发布 {cuts.length} 个独立单曲视频，共用本场次、视角与内容标签。未进行跨视频对齐，不加入连续视角切换。</p>}<p className="helper">仅发布你有权分享的视频，避免暴露他人的个人信息。</p></div>}
{error&&<p className="error" role="alert">{error}</p>}{busy&&<p className="busy" role="status"><Loader2 className="spin" size={16}/>{busy}</p>}<div className="dialog-actions">{step===2&&<button className="secondary" disabled={!!busy} onClick={()=>setStep(1)}>上一步</button>}<button className="primary" disabled={!!busy||!session||(!edit&&!media)||(split?(!cuts.length||!confirmed):(!songs.length&&!segment))} onClick={()=>step===1?setStep(2):void publish()}>{step===1?"下一步 · 整理片段":edit?"保存修改":split?`发布 ${cuts.length} 首歌并点亮现场`:"发布并点亮现场"}</button></div></DialogContent></Dialog>}


